# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Logoo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Logoo
pod 'ImageViewer.swift', '~> 3.0'

  target 'LogooTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LogooUITests' do
    # Pods for testing
  end

end
